services:
  playwright:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: playwright-framework
    working_dir: /app

    volumes:
      - ..:/app
      - /app/node_modules
      - ../playwright-report:/app/playwright-report
      - ../test-results:/app/test-results

    environment:
      BASE_URL: ${BASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      HEADLESS: true
      
    command: npx playwright test